### ISSUE TITLE
Request: [affiliate_logged_in] and [affiliate_logged_out]

### ISSUE THREAD

**Issue by flowdee** [affiliatewp/affiliatewp-affiliate-area-shortcodes#1]
Would be amazing to get [affiliate_logged_in] and [affiliate_logged_out] shortcodes in order to place some content only for logged in affiliates (e.g. special announcements etc.) or _not logged in_ people (e.g. some advertising / description to join the program)

**Comment by flowdee** [comment]
```
add_shortcode( 'affiliate_logged_in', array( $this, 'affiliate_logged_in' ) );  
add_shortcode( 'affiliate_logged_out', array( $this, 'affiliate_logged_out' ) );  

/**
* [affiliate_logged_in] shortcode
*
* @since  1.X
*/

function affiliate_logged_in( $atts, $content = null ) {
    if ( ! ( affwp_is_affiliate() && affwp_is_active_affiliate() ) ) {
        return;
    }

    return do_shortcode( $content );
}

/**
* [affiliate_logged_out] shortcode
*
* @since  1.X
*/

function affiliate_logged_out( $atts, $content = null ) {
    if ( ! ( affwp_is_affiliate() && affwp_is_active_affiliate() ) ) {
        return do_shortcode( $content );
    }

    return;
}
```
:blush:

**Comment by sumobi** [comment]
@flowdee the [affiliate_content] and [non_affiliate_content] should help you achieve this:

http://docs.affiliatewp.com/article/74-nonaffiliatecontent
http://docs.affiliatewp.com/article/73-affiliatecontent

**Comment by flowdee** [comment]
What a shame I didn't see this. I looked for "logged in" and not "content". Thanks!
