### ISSUE TITLE
Add shortcode for affiliate status text

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/affiliatewp-affiliate-area-shortcodes#11]
AffiliateWP's `[affiliate_area]` shortcode shows messages to the affiliate based on their status:
https://github.com/AffiliateWP/AffiliateWP/blob/master/templates/dashboard.php#L5-L17

Currently there's no way to show these messages when building a custom affiliate area using this add-on.

I propose a new shortcode called `[affiliate_status_messages]` or similar that can be placed wherever the site owner would like affiliates to see a message based on their status.

The shortcode by default would output each message that the `[affiliate_area]` shortcode does via the `dashboard.php` template file. 

If needed, the messages can be overridden via new shortcode attributes:

```
[affiliate_status_messages pending="Your affiliate application is pending" inactive="Your affiliate account isn't active, sorry!" rejected="I'm sorry, your application was rejected."]
```

**Comment by pippinsplugins** [comment]
I like it.

**Comment by sumobi** [comment]
Changed shortcode name to `[affiliate_area_notices]` which makes more sense. It also includes a notice when the profile has been updated.
