### ISSUE TITLE
Add shortcode for affiliate ID

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/affiliatewp-affiliate-area-shortcodes#2]
Would be handy to have a small shortcode that simply outputs the affiliate ID and/or username.

**Comment by worldtravlr** [comment]
:+1: Another cool option would be one to be able to display the Affiliates first and/or last name.  Currently I am using this - https://wordpress.org/plugins/user-shortcodes/ - to do that so I can welcome them and make it fell more personal in the user area, but would be cool if this could be done via short code and then it would require one less plugin :-)

_____


Relatedly, here are some other recommendations/requests for these from Issue #627 post:

* Add a shortcode to only show "Referral URL Stats" thats separate from "Referral URL Visits"
* Add a shortcode for "Order Details" That acts similar to the built in affiliate area tabs in that if the user has order details enabled, it will show the tables and if not, it would either not show anything or have some filler text like "This feature is not enabled for your account", etc.  If this filler text could be easily customize vie child theme and/or in the admin area that would be awesome.
  * Have option for Order Details shortcode to use pagination.  For example [affiliate_area_order_details pages=yes number_per_page=15]

Hope that helps and please let me know if you have any questions.

**Comment by sumobi** [comment]
@worldtravlr Will open separate issues on your shortcode ideas. The Order Details shortcode will be included from the Order details add-on, rather than this add-on/

**Comment by sumobi** [comment]
Opened issue on shortcode for order details here: https://github.com/affiliatewp/affiliatewp-order-details-for-affiliates/issues/9

**Comment by sumobi** [comment]
@worldtravlr Can you elaborate on "Add a shortcode to only show "Referral URL Stats" thats separate from "Referral URL Visits""?

Can you show me a screenshot of the exact information you want to only show?

**Comment by worldtravlr** [comment]
Thanks @sumobi and awesome work.  for the above question, I think you got it with the following:

[affiliate_campaign_stats]
[affiliate_area_visits]

I had a custom template that only worked if they were both shown in the same tab, but with the new short codes all is good there!  Thanks so much.

**Comment by sumobi** [comment]
@worldtravlr You're welcome!
