### ISSUE TITLE
Always load frontend scripts on the selected Affiliate Area page

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-affiliate-area-shortcodes#20]
The affiliate area shortcodes add-on uses `has_shortcode()` to detect the shortcode on a page, and then forces the `frontend.js` file to load using AffiliateWP's `affwp_force_frontend_scripts` filter.

Some 3rd party extensions allow the user to place shortcodes _outside_ of the `wp_posts` table so any call to `has_shortcode()` will fail.

As an example, the `[affiliate_area_urls]` shortcode may be placed in a custom WooCommerce My Account tab using a 3rd party extension. Since this shortcode is actually stored in `wp_options`, the `frontend.js` file does not load and when generating a URL, and so the input field no longer slides down to reveal the url (it performs a page load instead). This in turn is conflicting with another add-on, see: https://github.com/AffiliateWP/affiliatewp-affiliate-dashboard-sharing/issues/36

It seems rather common that customers add the shortcodes provided by AAS to WooCommerce's My Account page. For this use-case, and to cut down on support tickets, we could add a new conditional that checks the current page to see if it's the Affiliate Area. If one of the provided shortcodes exists on any endpoint of the my account page, the frontend.js file will load as expected.

The My Account page will need be selected as the affiliate area:

<img width="687" alt="Screen Shot 2019-03-21 at 3 36 03 PM" src="https://user-images.githubusercontent.com/52581/54796975-4745e580-4cb7-11e9-8885-757a8796f936.png">

For all other use-cases, where multiple shortcodes are being loaded outside the editor, on different pages, the customer could utilize the `affwp_force_frontend_scripts` filter directly and force the frontend script to load based on their current page.

**Comment by amdrew** [comment]
https://github.com/AffiliateWP/affiliatewp-affiliate-area-shortcodes/pull/21

@gspice Can you test this and see if it fixes https://github.com/AffiliateWP/affiliatewp-affiliate-dashboard-sharing/issues/36 for you?

**Comment by gspice** [comment]
@amdrew  Thank you!  Looks great on the sandbox test site :-)

<img width="952" alt="Screen Shot 2019-03-22 at 15 16 46" src="https://user-images.githubusercontent.com/3018245/54856064-fd103480-4cb5-11e9-9655-d0e159105a11.png">

**Comment by gspice** [comment]
This change has been applied to the customer's site and all is working well!
