### ISSUE TITLE
Add parameter to [affiliate_area_urls] to only display the url generator

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/affiliatewp-affiliate-area-shortcodes#26]
At times we've had the request to display only the URL generator using the `[affiliate_area_urls]` shortcode.  Suggestion is to add a parameter to this existing shortcode or create a new one for it. 

<img width="791" alt="Screen Shot 2019-10-03 at 14 30 58" src="https://user-images.githubusercontent.com/3018245/66165948-bdbe8b00-e5ea-11e9-89d7-27cd3c7fc01f.png">

**Comment by DrewAPicture** [comment]
Currently, it looks like `[affiliate_area_urls]` actually just loads the dashboard-tab-urls template directly. In order to support something like this we'd probably need to split up the template or output the URL generator into the template via a function so we could segregate it.

**Comment by worldtravlr** [comment]
Easiest option may be to specify a unique div around the shortcake and then hide the other elements via CSS.  A bit of a hack, but if the customer is looking for an easy to implement option it could work for now.

**Comment by DrewAPicture** [comment]
Note: See my [comment](https://github.com/AffiliateWP/affiliatewp-affiliate-area-shortcodes/issues/26#issuecomment-538276515) from October 4, 2019.

**Comment by alexstandiford** [comment]
I think we'd be better off writing a filter to make it possible to exclude the campaigns field, specifically.

The benefit of this is that we would be able to write the `add_filter`/`remove_filter` statements in the this plugin, and then add-in the `apply_filter` statement in core whenever we can.

This plays nice with backcompat, and provides a straightforward way to deploy without any weird chicken-and-egg problems.

Honestly, none of these are exactly great options but this one seems to be the least-disruptive.

PR: #31

**Comment by DrewAPicture** [comment]
After some discussion with @amdrew, we've decided to forego adding this functionality altogether.

@alexstandiford Thanks very much for the effort and time investigating this issue.
