### ISSUE TITLE
[affiliate_referrals] shortcode is not working

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-affiliate-area-shortcodes#28]
## Bug Report
When the [affiliate_referrals] shortcode is used it is not showing any information. A customer experience this and I was able to replicate. Here is the content of the [ticket](https://secure.helpscout.net/conversation/1117210735/148644?folderId=634609): 
>Im using Affiliate WP at latest version and [affiliate_referrals] is not working, im trying to make a custom affiliate page and I want to display the how many sells the affiliate has made, when I add the shortcode it does nothing.

>Im using other shortcodes and all its fine except this one, can you please check it?
 
### Expected behavior
When I add the [affiliate_referrals] shortcode to a page I expect referral information to be shown. 

### Actual behavior
When I add the [affiliate_referrals] shortcode to a page, nothing is shown.     

### Steps to reproduce the behavior 
1) Activate Affiliate Area Shortcodes
2) Add the [affiliate_referrals] shortcode to a page
3) View the page and no information shows 

### Information 
PHP Version: 7.3.5 and 7.3.15
AffiliateWP Version: 2.4.5, 2.5, and 2.5.1
WordPress Version: 5.3.2 and 5.4-RC3-47477
Affiliate Area Shortcodes Version: 1.1.7

**Comment by gspice** [comment]
When testing this is working for me, however, I found that you _have_ to use the status parameter as it shows at the bottom of the[ docs page for the Affiliate Area Shortcodes add-on ](https://docs.affiliatewp.com/article/726-affiliate-area-shortcodes-setup)

`[affiliate_referrals status="paid"]`

`[affiliate_referrals status="unpaid"]`

Also, the customer doesn't show any referrals in their system info file, and in that case it would not display anything even with the status values.

**Comment by michaelbeil** [comment]
@gspice thanks! That resolves it on my end and I'll let the customer know.
