### ISSUE TITLE
Add shortcode for campaign tracking table

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/affiliatewp-affiliate-area-shortcodes#3]
Add shortcode for the new campaign tracking table in v1.7. The [affiliate_area_stats] shortcode will show this however just like the other shortcodes included, it would be nice to show just the campaigns table on its own.

**Comment by worldtravlr** [comment]
Awesome!  Thanks @sumobi! +1

**Comment by sumobi** [comment]
@worldtravlr You're welcome!
