### ISSUE TITLE
Shortcode for affiliate's first/last name

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/affiliatewp-affiliate-area-shortcodes#6]
Currently to do this requires another plugin. It would be nice if this shortcode can do this so you don't need another plugin

**Comment by sumobi** [comment]
@worldtravlr I think I might only include a [affiliate_name] shortcode. This shortcode will use AffiliateWP's default function for retrieving the affiliate's name, which is actually their WordPress display name. 

It would be much better to show an affiliate their own name in the format that they specified in their profile. This is after all what the display name is for. IE, if they want to show both first and last name they could, or they could choose to just show their first name

![screen shot 2015-10-11 at 3 41 33 pm](https://cloud.githubusercontent.com/assets/52581/10414392/a02927c0-702e-11e5-88f7-3a951bd9663e.png)

**Comment by worldtravlr** [comment]
Thanks so much for implementing this Andrew!  Awesome.

Makes sense, but this will also add one more step for us when we set up an affiliate as we would like to call them by first name to make it seem less formal.  At the top of our affiliate area we have a title that says:

"Hello Griffin, Welcome to your affiliate headquarters!"

With seems like a nice, friendly welcome.  With this, unless we change their name in their profile settings, is will say:

"Hello Griffin Stewart, Welcome to your affiliate headquarters!"

Which seems less normal to me.  When do you call people by their first and last name?

Would it be a easy to add an option that would only use the first name optionally, so something like:

[affiliate_name first=yes last=no]

OR

[affiliate_name first=only]

As most affiliates may not be the most savy wordpress users and know where to change their name and this would enable us to provide what feels like a more friendly and less formal experience no matter what their default settings are.  Thoughts?

**Comment by sumobi** [comment]
@worldtravlr Fair point, I can add a parameter to the shortcode that forces the use of the first name, regardless of what is set in the display name. Something like [affiliate_name first_name="true"]

**Comment by sumobi** [comment]
@worldtravlr Going to call it `[affiliate_name first_name_only="true"]` so it's very clear on what it does.

**Comment by sumobi** [comment]
Update is out

**Comment by worldtravlr** [comment]
Awesome!  Thanks so much again @sumobi!  Really appreciate it and have already implemented! :+1:

**Comment by sumobi** [comment]
You're welcome!
