### ISSUE TITLE
Add Show Affiliate Coupons shortcode

### ISSUE THREAD

**Issue by michaelbeil** [affiliatewp/affiliatewp-affiliate-area-shortcodes#8]
We should add a shortcode to display the Show Affiliate Coupons in the affiliate area.

https://secure.helpscout.net/conversation/138532745/21152/

**Comment by worldtravlr** [comment]
:+1:

**Comment by sumobi** [comment]
The affiliate area shortcodes add-on is independent of other add-ons, eg each shortcode inside this add-on should just work, with only AffiliateWP active and no other add-on needed. If someone used a shortcode to display the coupons, but didn't have the show affiliate coupons add-on installed, it would seem broken, and nothing would display.

For this reason, the shortcode is actually already included in the Show Affiliate Coupons add-on:
https://github.com/affiliatewp/affiliatewp-show-affiliate-coupons/blob/master/affiliatewp-show-affiliate-coupons.php#L219

**Comment by sumobi** [comment]
This is also the same with the Order Details for Affiliates add-on, shortcode is included in that add-on, not this one: https://github.com/affiliatewp/affiliatewp-order-details-for-affiliates/blob/master/includes/class-shortcodes.php#L11

**Comment by michaelbeil** [comment]
This is available on any page you can use the [affiliate_coupons] shortcode on. 

Simply add [affiliate_coupons] to the affiliate area and you are set.
